spring.application.name=examen-vuelos
spring.datasource.url=jdbc:postgresql://localhost:5432/examen_vuelos
spring.datasource.username=postgres
spring.datasource.password=jh.txx4$w
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true